services:
  octiv-booker:
    container_name: octiv-scheduler
    build:
      context: .
      target: builder
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - OCTIV_EMAIL=${OCTIV_EMAIL}
      - OCTIV_PASSWORD=${OCTIV_PASSWORD}
      - DISCOVERY_CRON=${DISCOVERY_CRON:-0 4 * * *}
      - DRY_RUN=${DRY_RUN:-true}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}
    volumes:
      - ./src:/app/src
      - ./wishlist.json:/app/wishlist.json
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - /app/node_modules
    command: yarn start
