services:
  octiv-booker:
    container_name: octiv-scheduler
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs:/app/logs # if we add file logging later
      - ./wishlist.json:/app/wishlist.json
